defaults:
  - _self_
  - model: orbit #orbit - random_forest - sarimax - lstm - gru - prophet
  - dataset_loader: Bitmex #Bitmex
  - metrics

validation_method: simple #simple - cross_validation
symbol: XBT
# load_path: C:\Users\risha\Downloads\CryptoPrediction_new\CryptoPredictions\data\ETHUSD-1h-data.csv
#load_path: C:\Users\risha\Downloads\CryptoPrediction_new\CryptoPredictions\data\ETHUSD-1d-data.csv
load_path: C:\Users\risha\Downloads\CryptoPrediction_new\CryptoPredictions\data\XBTUSD-1d-data.csv
#load_path: C:\Users\risha\Downloads\CryptoPrediction_new\CryptoPredictions\data\XBTUSD-1h-data.csv
save_dir: 
dataset_path: